Capitales = {"Aguascalientes":"Aguascalientes",
"Baja California":"Mexicali",
"Baja California Sur":"La Paz",
"Campeche":"Campeche",
"Chiapas":"Tuxtla Gutiérrez",
"Chihuahua":"Chihuahua",
"Ciudad De México":"Ciudad de México",
"Coahuila":"Saltillo",
"Colima":"Colima",
"Durango":"Victoria de Durango",
"Guanajuato":"Guanajuato",
"Guerrero":"Chilpancingo de los Bravo",
"Hidalgo":"Pachuca de Soto",
"Jalisco":"Guadalajara",
"Estado De México":"Toluca de Lerdo",
"Michoacán":"Morelia",
"Morelos":"Cuernavaca",
"Nayarit":"Tepic",
"Nuevo León":"Monterrey",
"Oaxaca":"Oaxaca de Juárez",
"Puebla":"Puebla de Zaragoza",
"Querétaro":"Santiago de Querétaro",
"Quintana Roo":"Chetumal",
"San Luis Potosí":"San Luis Potosí",
"Sinaloa":"Culiacán Rosales",
"Sonora":"Hermosillo",
"Tabasco":"Villahermosa",
"Tamaulipas":"Ciudad Victoria",
"Tlaxcala":"Tlaxcala de Xicohténcatl",
"Veracruz":"Xalapa-Enríquez",
"Yucatán":"Mérida",
"Zacatecas":"Zacatecas"}
vinput=''
while vinput.lower() != "terminado":
    print("Introduzca de cuál Estado desea saber la capital, si ya terminó escriba 'terminado' ")
    print("La capital es " + Capitales.get(input().title()))
